# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47055e3dacd9b14b17291dd7e8f82b0069d03eac36b92b7501a515d99b65a15ef35c61c7a2905b42e3864df1b0f8063fe5e4818f316fd59d331aaa913c89494e

test:
  secret_key_base: d7e209d0697a23928cab8c23c5c1cac5834fc8254863c3b459770cfb33851f51faff4d0f02f85bd4fb51d9d2ba387e93437cfa2233e6da75776fa766a29eab99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
